#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/boot'

color_hash = {
  '#title#' => 'white',
  '#item#' => 'gold',
  '#item-placeholder#' => 'yellow',
  '#tags#' => 'white',
  '#tags-filter#' => 'gold',
  '#tags-dragged#' => 'yellow',
  '#dropping-into#' => 'orange',
  '#selector-back#' => '#000',
  '#selector-front#' => '#fff',
  '#editor-back#' => '#000',
  '#editor-front#' => '#fff',
}

# (◕ ” ◕)
# #490A3D  lila
# #BD1550  rosa
# #E97F02  naranja
# #F8CA00  amarillo
# #8A9B0F  verde
# http://www.colourlovers.com/palette//(%E2%97%95%20%E2%80%9D%20%E2%97%95)

eyes = {
  '#title#' => '#BD1550',
  '#item#' => '#E97F02',
  '#item-placeholder#' => '#F8CA00',
  '#tags#' => '#8A9B0F',
  '#tags-filter#' => '#F8CA00',
  '#tags-dragged#' => '#8A9B0F',
  '#dropping-into#' => '#490A3D',
  '#selector-back#' => 'black',
  '#selector-front#' => 'white',
  '#editor-back#' => 'black',
  '#editor-front#' => 'white',
}

color_hash=eyes if ARGV[0] == 'eyes'
# ARGV.each_index { |i| color_hash["#color#{i+1}#"]=ARGV[i] }

SRC_FILE = File.join(RAILS_ROOT,'config','main.css')
DST_FILE = File.join(RAILS_ROOT,'public','stylesheets','main.css')

if !File.exists?(SRC_FILE) then
  puts "src file: '#{SRC_FILE}' does not exist"
  exit
end

lines = IO.readlines(SRC_FILE)
lines.map! do |x|
  if x =~ /#.+#/
    color_hash.each do |c,t|
      x.gsub!(c,t)
    end
  end
  x
end

File.open(DST_FILE, "w") { |f| f.puts lines.join() }
